@url = http://localhost:5248

### Register a new user
POST {{url}}/api/v1/auth/register
Accept: application/json
Content-Type: application/json

{
    "Username": "user",
    "Password": "passwordexele",
    "Email": "email@addressexple.com"
}

### Login with existing user
POST {{url}}/api/v1/auth/login
Accept: application/json
Content-Type: application/json

{
    "Email": "email@addressexple.com",
    "Password": "passwordexele"
}