@url = http://localhost:5248

POST {{url}}/api/v1/auth/register
Accept: application/json
Content-Type: application/json

{
    "Username": "user",
    "Password": "passwordexele",
    "EmailAddress": "email@addressexple.com"
}
