@url = http://localhost:5248

POST {{url}}/api/v1/user/register
Accept: application/json
Content-Type: application/json

{
    "Username": "username",
    "Password": "password",
    "EmailAddress": "emailaddress"
}
