name: Build and Push Docker image

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --no-restore --configuration Release

      - name: Run unit tests
        run: dotnet test tests/Location404.Auth.Domain.UnitTests/Location404.Auth.Domain.UnitTests.csproj --no-build --configuration Release --logger "trx;LogFileName=test_results.trx"

  docker:
    runs-on: ubuntu-latest
    needs: test   # só executa se os testes passarem

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/location404/user.identity.service:latest .

      - name: Push Docker image
        run: |
          docker push ghcr.io/location404/user.identity.service:latest
